const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const apps=require('../data/apps.json');
const translations=require('../data/translations.json');
const {card,filters,escape}=require('../assets/home.js');
let html=fs.readFileSync(path.join(root,'src/index.template.html'),'utf8');
html=html.replace('{{CARDS}}',apps.map(app=>card(app,'ko')).join('\n')).replace('{{FILTERS}}',filters('ko'));
html=html.replace('{{ICONS}}',apps.map(app=>`<a href="#app-${app.slug}" aria-label="${escape(app.name)}"><img src="${app.icon}" alt="${escape(app.name)}" width="38" height="38" loading="lazy"></a>`).join(''));
html=html.replace(/(<([a-z0-9]+)\b[^>]*data-i18n="([^"]+)"[^>]*>)([^<]*)(<\/\2>)/g,(all,start,tag,key,content,end)=>start+escape(translations.ko[key])+end);
html=html.replace(/(<meta name="description" content=")[^"]*/, '$1'+escape(translations.ko['meta.desc']));
html=html.replace(/(<meta property="og:description" content=")[^"]*/, '$1'+escape(translations.ko['meta.desc']));
html=html.replace(/(<meta name="twitter:description" content=")[^"]*/, '$1'+escape(translations.ko['meta.desc']));
// Keep the structured data aligned with the visible app catalog.
html=html.replace(/(<script type="application\/ld\+json" id="ld-json">)([\s\S]*?)(<\/script>)/,(all,start,json,end)=>{
 const schema=JSON.parse(json);
 if(schema['@graph']) for(const item of schema['@graph']) if(item['@type']==='WebSite'||item['@type']==='Organization') if(item.description)item.description=translations.ko['meta.desc'];
 return start+JSON.stringify(schema,null,2)+end;
});
// Accurate intrinsic dimensions avoid shifts as the hero photographs arrive.
for(const slug of ['maeum','snaplog','chaengkim']){
 const shot=apps.find(a=>a.slug===slug).screenshots[0];
 const re=new RegExp('(<img src="'+shot.src.replaceAll('.','\\.')+'"[^>]*width=")[0-9]+(" height=")[0-9]+');
 html=html.replace(re,'$1'+shot.width+'$2'+shot.height);
}
fs.writeFileSync(path.join(root,'index.html'),html.replace(/[ \t]+$/gm,''));
fs.writeFileSync(path.join(root,'assets/catalog.js'),'/* Generated by node scripts/build.cjs */\nconst KENNETH_DATA = '+JSON.stringify({apps,translations}).replaceAll('<','\\u003c')+';\n');
console.log(`Built ${apps.length} app cards with ${apps.reduce((sum,a)=>sum+a.screenshots.length,0)} verified store screenshots.`);
